import {createRouter, createWebHistory} from "vue-router";

const router=createRouter({
    history: createWebHistory(),
    routes:[
        {
            path:'/',
            name:'Home',
            meta:{title:'主页'},
            component:()=>import('../views/Home.vue')
        },
        {
            path:'/day01',
            name:'day01',
            meta:{title:'第一个'},
            component:()=>import('../views/Day1/index.vue')
        },
        {
            path:'/day02',
            name:'day02',
            meta:{title:'第二个'},
            component:()=>import('../views/Day2/index.vue')
        },
        {
            path:'/day03',
            redirect:'/day03/page01',
            name:'day03',
            meta:{title:'第三个'},
            component:()=>import('../views/Day3/index.vue'),
            children:[
                {
                    path:'/day03/page01',
                    component:()=>import('../views/Day3/pages/page01.vue')
                },
                {
                    path:'/day03/page02',
                    component:()=>import('../views/Day3/pages/page02.vue')
                },
                {
                    path:'/day03/page03',
                    component:()=>import('../views/Day3/pages/page03.vue')
                },
            ]
        },
        {
            path:'/day04',
            name:'day04',
            meta:{title:'第四个'},
            component:()=>import('../views/Day4/index.vue')
        },
        {
            path:'/day05',
            name:'day05',
            meta:{title:'第五个'},
            component:()=>import('../views/Day5/index.vue')
        },
        {
            path:'/day06',
            name:'day06',
            meta:{title:'第六个'},
            component:()=>import('../views/Day6/index.vue')
        },
        {
            path:'/day07',
            name:'day07',
            meta:{title:'第七个'},
            component:()=>import('../views/Day7/index.vue')
        },{
            path:'/day08',
            name:'day08',
            meta:{title:'第八个'},
            component:()=>import('../views/Day8/index.vue')
        },
        {
            path:'/day09',
            name:'day09',
            meta:{title:'第九个'},
            component:()=>import('../views/Day9/index.vue')
        },
        {
            path:'/day10',
            name:'day10',
            meta:{title:'第十个'},
            component:()=>import('../views/Day10/index.vue')
        },
    ]
})

export default router